feat: enable optional custom date format
janraasch/hugo-bearblog pull request #23
Opened 2021-04-06 07:10 UTC by akirabaruah

Adds a .Site.Params.dateFormat setting to let users specify a Hugo-style
date format string for content. Previously, the date format was
hardcoded to "02 Jan, 2006", presumably to match the original BearBlog
style. This format gets used by default if the new "dateFormat" setting
is absent from the site config.

2021-04-09 15:35 UTC, janraasch requested changes
Hi @akirabaruah, 

thank you very much for your contribution 🙏.

> Previously, the date format was hardcoded to "02 Jan, 2006", presumably to match the original BearBlog style.

That is 💯 percent correct 😄 👌.

I really like that you took care to add documentation, but I would like you to move this to the other `params` examples and explanations inside the exampleSite's config.toml.

Have great weekend 🏝

2021-04-09 15:35 UTC, janraasch commented on README.md
> +### Customizing date format
Could you move this to the `exampleSite/config.toml`? I think that makes more sense for a `params`-key.

2021-04-09 15:35 UTC, janraasch commented on layouts/_default/list.html
> +            {{ .Date.Format (default "02 Jan, 2006" .Site.Params.dateFormat) }}
👍🏻

2021-04-09 15:35 UTC, janraasch commented on layouts/_default/single.html
> +      {{ .Date.Format (default "02 Jan, 2006" .Site.Params.dateFormat) }}
👍🏻

2021-04-09 19:53 UTC, akirabaruah commented on README.md
> +### Customizing date format
Sounds good :+1: done!

2021-04-09 19:55 UTC, akirabaruah commented
Thanks for the prompt and cheerful review! :)

2021-04-12 15:17 UTC, janraasch approved these changes
💯 🏌️‍♂️ 😁.

Thank you, @akirabaruah 🤝.

2021-04-12 15:18 UTC, merged